### ISSUE TITLE
Github stars badges within table cell doesn't work

### ISSUE THREAD

**Issue by sammhho** [PaulieScanlon/gatsby-remark-sticky-table#2]
Hi @PaulieScanlon , thx for open-sourcing this plug-in, looks really nice!

I'm a total newbie to web, React and Gatsby, excuse me if I'm asking stupid questions.
I have a markdown page transformed by remark, where a table has some cells using the Github stars badge with this syntax:
`[![GitHub stars](https://img.shields.io/github/stars/Naereen/StrapDown.js.svg?style=social&label=Star&maxAge=2592000)](https://GitHub.com/Naereen/StrapDown.js/stargazers/)`
which I copied from [here](https://github.com/Naereen/badges).

Without applying sticky-table, the cell works fine for showing the badge, but the table has no borders rendered.
(I suppose this is due to gatsby-transformer-remark 's bug since it's supposed to support Github style? or it needs extra css to work!?)
Now after applying sticky-table, the cell rendered into text "GitHub stars".

Is this somewhat a missed corner case in sticky-table's code? Any plan to patch if so? 
(I would have try to write a fix and do PR if I were capable, but since I'm so new to web...)
Or is there a work-around I can apply in my code base?

**Comment by PaulieScanlon** [comment]
Hey @sammhho Thanks for raising the issue! I'm not entirely sure why `remark` isn't escaping the image short code, probably something to do with the way i'm passing the child nodes through the plugin and rendering to string... but


This should get you out of a fix


instead of using the markdown short code in the table eg

```
| Head one            | Head two | Head three |
| ------------------- | -------- | ---------- |
| [GitHub stars](url) | cell two | cell three |
``` 
use an image tag and add the `src` and `alt` yourself

```
| Head one                                | Head two | Head three |
| --------------------------------------- | -------- | ---------- |
| <img src='url' alt='GitHub stars'/> | cell two | cell three |
```

Which renders as 👇

| Head one                                                                                                                            | Head two | Head three |
| ----------------------------------------------------------------------------------------------------------------------------------- | -------- | ---------- |
| <img src='https://img.shields.io/github/stars/Naereen/StrapDown.js.svg?style=social&label=Star&maxAge=2592000' alt='GitHub stars'/> | cell two | cell three |


Oh and with regard to styles, in either case you'll probably need to add some kind of markdown styles. If you want your markdown to look like GitHub [sindresorhus](https://github.com/sindresorhus/github-markdown-css/blob/gh-pages/index.html) has an excellent bit of css for that.

**Comment by sammhho** [comment]
@PaulieScanlon thx a lot for the quick response and the pointers, I got it working~

**Comment by PaulieScanlon** [comment]
@sammhho whey!!! Well done! Stick at it!
